version: "3.7"
services:
  wordpress:
    image: endeavouresu/endeavourwp:latest
    volumes:
      - ${WEBAPP_STORAGE_HOME}/home:/home
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot:/var/www/html
      - ${WEBAPP_STORAGE_HOME}/LogFiles:/var/log
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: endvrdb1.mysql.database.azure.com
      WORDPRESS_DB_USER: wpendeavour@endvrdb1
      WORDPRESS_DB_PASSWORD: 1#aqkfJAG3V2YqpI!57GmrqS#0JgVhY9@7A12RQs
      WORDPRESS_DB_NAME: endvrwpdb1
      WEBSITES_ENABLE_APP_SERVICE_STORAGE: TRUE
